# Generated by Django 3.1.6 on 2021-02-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='main_photo/', verbose_name='Главное фото')),
                ('image2', models.ImageField(upload_to='shots/', verbose_name='Изображение-2')),
                ('image3', models.ImageField(upload_to='shots/', verbose_name='Изображение-3')),
                ('image4', models.ImageField(upload_to='shots/', verbose_name='Изображение-4')),
                ('places', models.CharField(max_length=300, verbose_name='Планируемые места')),
                ('payment', models.CharField(max_length=300, verbose_name='Способы оплаты')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
            },
        ),
    ]
