# Generated by Django 3.1.6 on 2021-02-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='payment',
            field=models.TextField(verbose_name='Способы оплаты'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='places',
            field=models.TextField(verbose_name='Планируемые места'),
        ),
    ]
